doc-valid-idents = [
    "MaxNovo",
    "MaxQuant",
    "..",
    "GNOme",
    "ProForma",
    "OPair",
    "MSFragger",
    "MZTab",
    "PSM_ID",
    "DeepNovo",
    "PGPointNovo",
]
avoid-breaking-exported-api = false
check-private-items = true
